// The starting content, copied into server/data/content.json the first time the
// server runs. After that the store is the source of truth and this file is
// only history — editing it changes nothing.
//
// Text the visitor reads is stored per language ({ en, sq, it }). `medium` and
// `form` are keys the client translates instead of stored prose, so adding a
// painting in the admin means picking from a list rather than writing the same
// words in three languages. Sizes in centimetres need no translation.
export const artist = {
  id: "marsila-bitri",
  name: "Marsila Bitri",
  studio: "Marsila Bitri Art",
  email: "hello@marsilabitri.art",
  statement: {
    en: "I paint to preserve the purest version of who I am, untouched, unaltered, and free.",
    sq: "Unë pikturoj për të qenë vetvetja e pacenuar.",
    it: "Dipingo per custodire la versione più pura di ciò che sono: intatta, inalterata e libera.",
  },
  // Short form for the home page; the full statement lives in `bio`.
  intro: {
    en: "Born in Sarandë and based in Tirana, Marsila Bitri is an architect and painter. Painting has been with her since childhood — a space where memory, emotion and inner reflection come together.",
    sq: "E lindur në Sarandë dhe me bazë në Tiranë, Marsila Bitri është arkitekte dhe piktore. Piktura e ka shoqëruar që në fëmijëri, si një hapësirë e brendshme reflektimi dhe ndjeshmërie.",
    it: "Nata a Saranda e con base a Tirana, Marsila Bitri è architetta e pittrice. La pittura l'accompagna fin dall'infanzia, come uno spazio interiore di riflessione e sensibilità.",
  },
  bio: {
    en: [
      "Born in the coastal city of Sarandë and now based in Tirana, Marsila Bitri is an architect and artist whose connection with painting began in childhood. Over the years, painting has evolved into a deeply personal language — a space where memory, emotion, intuition, and inner reflection come together.",
      "Her work is rooted in the subtle complexity of human relationships, in the shifting landscapes of emotion, and in an enduring curiosity about human nature. Each painting emerges as an intimate reflection of a particular state of mind, translating what is often difficult to express through words into color, form, and atmosphere.",
      "The sea holds a singular place within her artistic world. More than a recurring image, it becomes a presence — a source of memory, depth, movement, and contemplation. Through color and dimension, the sea often carries both a sense of belonging and an infinite emotional distance, becoming a quiet metaphor for the inner self.",
      "At times, her work also turns outward, responding to the tensions, concerns, and realities of contemporary Albanian life. These pieces become subtle reflections on the world around her, where personal sensitivity meets collective experience.",
      "For Marsila, painting is ultimately an act of authenticity — a way of returning to the essential self, of preserving an inner freedom, and of remaining wholly and unapologetically her own.",
    ],
    sq: [
      "Marsila Bitri ka lindur në Sarandë dhe zhvillon prej vitesh karrierën e saj si arkitekte në Tiranë. Piktura e ka shoqëruar që në fëmijëri, duke u kthyer me kohën në një hapësirë të brendshme reflektimi, ndjeshmërie dhe shprehjeje personale.",
      "Në qendër të krijimtarisë së saj qëndrojnë marrëdhëniet ndërnjerëzore, gjendjet shpirtërore dhe kurioziteti ndaj natyrës njerëzore. Një vend të veçantë zë marrëdhënia me detin, e përcjellë përmes ngjyrës, dimensionit dhe thellësisë, si kujtesë, ndjesi dhe mendim.",
      "Herë pas here, veprat e saj reflektojnë edhe shqetësimet dhe realitetin aktual shqiptar. Për Marsilën, piktura mbetet mbi të gjitha një mënyrë për të ruajtur autenticitetin dhe për të qenë vetvetja — e lirë dhe e pacenuar.",
    ],
    it: [
      "Nata nella città costiera di Saranda e oggi con base a Tirana, Marsila Bitri è architetta e artista, legata alla pittura fin dall'infanzia. Con gli anni la pittura è diventata un linguaggio profondamente personale — uno spazio in cui memoria, emozione, intuizione e riflessione interiore si incontrano.",
      "Il suo lavoro nasce dalla complessità sottile delle relazioni umane, dai paesaggi mutevoli delle emozioni e da una curiosità costante verso la natura umana. Ogni dipinto è il riflesso intimo di uno stato d'animo e traduce in colore, forma e atmosfera ciò che le parole faticano a dire.",
      "Il mare occupa un posto unico nel suo mondo artistico. Più che un'immagine ricorrente, diventa una presenza — fonte di memoria, profondità, movimento e contemplazione. Attraverso il colore e la dimensione, il mare porta con sé insieme un senso di appartenenza e una distanza emotiva infinita, metafora silenziosa del sé interiore.",
      "A volte il suo lavoro si volge verso l'esterno e risponde alle tensioni, alle inquietudini e alla realtà dell'Albania contemporanea. Sono opere che riflettono sul mondo intorno a lei, dove la sensibilità personale incontra l'esperienza collettiva.",
      "Per Marsila la pittura è soprattutto un atto di autenticità — un modo di tornare al sé essenziale, di custodire una libertà interiore e di restare pienamente se stessa.",
    ],
  },
  birthplace: {
    en: "Sarandë",
    sq: "Sarandë",
    it: "Saranda",
  },
  location: {
    en: "Tirana",
    sq: "Tiranë",
    it: "Tirana",
  },
  instagram: "https://instagram.com/",
};

// Order follows Marsila's own catalogue document, which pairs every text with a
// photo of the canvas — that pairing is what decides the image on each entry.
export const artworks = [
  {
    id: "a-man-and-his-circus",
    title: {
      en: "A Man and His Circus",
      sq: "Njeriu me cirk",
      it: "L'uomo e il suo circo",
    },
    year: "",
    medium: "acrylic",
    form: "triptych",
    dimensions: "3 × 50 × 110 cm",
    available: true,
    published: true,
    image: "/media/carousel.jpg",
    images: ["/media/carousel.jpg", "/media/carousel-2.jpg"],
    description: {
      en: "The struggle and duality of modern man, caught in the trap of imitating the leader, stripped of identity and a voice of his own. A life turned into a circus: he laughs when others laugh, cries when others cry, while the “child” within remains imprisoned behind invisible bars.",
      sq: "Lufta dhe dualiteti i njeriut të sotëm, i zënë në kurthin e imitimit të liderit, pa identitet e pa një zë të vetin. Një jetë e kaluar si në cirk: qesh kur të tjerët qeshin, qan kur të tjerët qajnë, ndërsa “fëmija” brenda tij mbetet i burgosur pas hekurave të padukshëm.",
      it: "La lotta e la dualità dell'uomo di oggi, intrappolato nell'imitazione del leader, privato della propria identità e della propria voce. Una vita trasformata in circo: ride quando ridono gli altri, piange quando piangono gli altri, mentre il “bambino” dentro di lui resta prigioniero dietro sbarre invisibili.",
    },
  },
  {
    id: "duality-city",
    title: { en: "Duality", sq: "Dualitet", it: "Dualità" },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "50 × 70 cm",
    available: true,
    published: true,
    image: "/media/red-and-grid.jpg",
    images: ["/media/red-and-grid.jpg"],
    description: {
      en: "Amorphous beings wander through a city without memory, among empty streets and extinguished souls. We are as close as we appear, yet as distant as we feel — divided by a silent flow of lava, by a hell that slowly runs between us.",
      sq: "Krijesa amorfe enden në një qytet pa kujtesë, mes rrugësh të zbrazura dhe shpirtrash të fikur. Jemi aq pranë sa dukemi, e aq larg sa ndihemi — të ndarë nga një llavë e heshtur, një ferr që rrjedh mes nesh.",
      it: "Creature amorfe vagano in una città senza memoria, tra strade vuote e anime spente. Siamo vicini quanto sembriamo e lontani quanto ci sentiamo — divisi da una lava silenziosa, da un inferno che scorre lento tra noi.",
    },
  },
  {
    id: "the-struggle-within",
    title: {
      en: "The Struggle Within",
      sq: "Përplasja e Brendshme",
      it: "La lotta interiore",
    },
    year: "",
    medium: "acrylic",
    form: "triptych",
    dimensions: "3 × 50 × 110 cm",
    available: true,
    published: true,
    image: "/media/heart-triptych.jpg",
    images: ["/media/heart-triptych.jpg"],
    description: {
      en: "The eternal struggle between the heart, the mind, the gut, and the Holy Spirit.",
      sq: "Lufta e përjetshme mes zemrës, arsyes, instinktit dhe Shpirtit të Shenjtë.",
      it: "L'eterna lotta tra il cuore, la mente, l'istinto e lo Spirito Santo.",
    },
  },
  {
    id: "arcade-of-veins",
    title: {
      en: "The Arcade of Veins",
      sq: "Arkada e venave",
      it: "L'arcata delle vene",
    },
    year: "",
    medium: "acrylic",
    form: "diptych",
    dimensions: "2 × 50 × 110 cm",
    available: true,
    published: true,
    image: "/media/veins-and-flowers.jpg",
    images: ["/media/veins-and-flowers.jpg"],
    description: {
      en: "The heart reflects what remains silent, sealed deep within the arcade of the soul.",
      sq: "Zemra reflekton atë që hesht, të mbyllur thellë në arkadën e shpirtit.",
      it: "Il cuore riflette ciò che tace, sigillato nel profondo dell'arcata dell'anima.",
    },
  },
  {
    id: "intertwined",
    title: { en: "Intertwined", sq: "Të Ndërthurur", it: "Intrecciati" },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "",
    available: true,
    published: true,
    // Shown as the home page cover; a portrait canvas suits that frame.
    featured: true,
    image: "/media/red-figure.jpg",
    images: ["/media/red-figure.jpg", "/media/red-figure-2.jpg"],
    description: {
      en: "A body within a body, suspended within a mind.",
      sq: "Një trup brenda një trupi, pezull në thellësinë e një mendjeje.",
      it: "Un corpo dentro un corpo, sospeso nella profondità di una mente.",
    },
  },
  {
    id: "woman-with-a-bronze-leaf",
    title: {
      en: "Woman with a Bronze Leaf",
      sq: "Gruaja me Gjethe të Bronzta",
      it: "Donna con foglia di bronzo",
    },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "70 × 100 cm",
    available: true,
    published: true,
    image: "/media/face-with-leaf.jpg",
    images: ["/media/face-with-leaf.jpg"],
    description: {
      en: "Vanity and the endless effort to preserve outer beauty, set against the thoughts that slowly wither the beauty within — if it still exists.",
      sq: "Vaniteti dhe përpjekja e pandërprerë për të ruajtur bukurinë e jashtme, përballë përsiatjeve që venitin ngadalë bukurinë e brendshme — nëse ajo ende ekziston.",
      it: "La vanità e lo sforzo incessante di preservare la bellezza esteriore, di fronte ai pensieri che lentamente consumano quella interiore — se ancora esiste.",
    },
  },
  {
    id: "eclipse-of-mind-and-heart",
    title: {
      en: "The Eclipse of Mind and Heart upon the Cross",
      sq: "Eklipsi i Mendjes dhe Zemrës mbi Kryq",
      it: "L'eclissi della mente e del cuore sulla croce",
    },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "100 × 120 cm",
    available: true,
    published: true,
    image: "/media/heart-and-branches.jpg",
    images: ["/media/heart-and-branches.jpg"],
    description: {
      en: "Opposing beings collide endlessly, while a deep abyss opens between them — where the mind denies what the heart still dares to feel.",
      sq: "Zemra pulson mes degëve të një bote të brendshme, ku rrënjët, drita dhe hija ndërthuren. Dy qenie të kundërta rropaten në një përplasje të pafund, ndërsa mes tyre hapet një humnerë.",
      it: "Esseri opposti si scontrano senza fine, mentre tra loro si apre un abisso profondo — dove la mente nega ciò che il cuore osa ancora sentire.",
    },
  },
  {
    id: "fragmented-nude",
    title: { en: "Fragmented Nude", sq: "Nudo e Copëzuar", it: "Nudo frammentato" },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "100 × 120 cm",
    available: true,
    published: true,
    image: "/media/blue-figures.jpg",
    images: ["/media/blue-figures.jpg"],
    description: {
      en: "A body scattered into fragments, almost disconnected from one another. A self-reflection on the self and on the inner light that still remains present.",
      sq: "Një trup i ndarë në fragmente, ku vetvetja humbet formën, por drita e brendshme mbetet.",
      it: "Un corpo disperso in frammenti, quasi scollegati l'uno dall'altro. Una riflessione su di sé e sulla luce interiore che ancora resta.",
    },
  },
  {
    id: "duality-chance",
    title: { en: "Duality", sq: "Dualitet", it: "Dualità" },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "80 × 90 cm",
    available: true,
    published: true,
    image: "/media/cards.jpg",
    images: ["/media/cards.jpg"],
    description: {
      en: "Amorphous beings adrift in the currents of chance.",
      sq: "Krijesa amorfe enden në fatin e së rastësishmes, mes formës dhe shpërbërjes.",
      it: "Creature amorfe alla deriva nelle correnti del caso, tra forma e dissoluzione.",
    },
  },
  {
    id: "fluid-nudity",
    title: { en: "Fluid Nudity", sq: "Nuditet Fluid", it: "Nudità fluida" },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "100 × 120 cm",
    available: true,
    published: true,
    image: "/media/blue-current.jpg",
    images: ["/media/blue-current.jpg", "/media/blue-current-2.jpg"],
    description: {
      en: "A nude figure drifting through weary eyes — a boundless form, forever dissolving.",
      sq: "Një nudo që rrëshqet mes syve të mpakur, si formë pa kufij.",
      it: "Una figura nuda che scivola tra occhi stanchi — una forma senza confini, che si dissolve di continuo.",
    },
  },
  {
    id: "sea-series-sunset",
    title: { en: "Sea Series", sq: "Seritë e Detit", it: "Serie del mare" },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "40 × 50 cm",
    available: true,
    published: true,
    image: "/media/bands.jpg",
    images: ["/media/bands.jpg"],
    description: {
      en: "The red of sunset spills into dusk, as the sky slowly fades and the light dissolves along the horizon.",
      sq: "E kuqja e perëndimit derdhet mbi muzg, ndërsa qielli zbehet ngadalë dhe drita shuhet në horizont.",
      it: "Il rosso del tramonto si riversa nel crepuscolo, mentre il cielo sbiadisce lentamente e la luce si dissolve all'orizzonte.",
    },
  },
  {
    id: "the-rabbit-hole",
    title: { en: "The Rabbit Hole", sq: "Vrima e Lepurit", it: "La tana del coniglio" },
    year: "",
    // The catalogue omits the medium for this one, so the specs line drops it.
    medium: "",
    form: "",
    dimensions: "90 × 130 cm",
    available: true,
    published: true,
    image: "/media/violet-form.jpg",
    images: ["/media/violet-form.jpg"],
    description: {
      en: "The symmetry of the unknown, where reality loses its form and the mind follows paths with no return.",
      sq: "Simetria e së panjohurës, ku realiteti humbet formën dhe mendja ndjek shtigje pa kthim.",
      it: "La simmetria dell'ignoto, dove la realtà perde la forma e la mente segue sentieri senza ritorno.",
    },
  },
  {
    id: "sea-series-depth",
    title: { en: "Sea Series", sq: "Seritë e Detit", it: "Serie del mare" },
    year: "",
    medium: "acrylic",
    form: "",
    dimensions: "90 × 120 cm",
    available: true,
    published: true,
    image: "/media/horizon.jpg",
    images: ["/media/horizon.jpg", "/media/horizon-2.jpg"],
    description: {
      en: "A deep sea breathes among the waves, beneath the silence of a tranquil sky.",
      sq: "Një det i thellë frymon mbi dallgë, nën heshtjen e një qielli të qetë.",
      it: "Un mare profondo respira tra le onde, sotto il silenzio di un cielo quieto.",
    },
  },
  {
    // The catalogue closes with "there is also a blue nude, 90x130" and nothing
    // more, so the title here is a placeholder and there is no text yet.
    id: "blue-nude",
    title: { en: "Blue Nude", sq: "Nudo blu", it: "Nudo blu" },
    year: "",
    medium: "",
    form: "",
    dimensions: "90 × 130 cm",
    available: true,
    published: true,
    image: "/media/seated-figure.jpg",
    images: ["/media/seated-figure.jpg"],
    description: "",
  },
];
